# Fine-grid job audit v3

Controlla lo stato di `graphs_fine_grid` per ogni città considerando tutte le trasformazioni previste:

- `original`
- traduzioni cardinali `trans_*`
- rotazioni `rot_*`
- scale anisotrope `scale_ns_*` e `scale_ew_*`

Una variante con `on_land=False` viene considerata **processata ma rigettata**: non va rilanciata.
Una variante va rilanciata solo se è attesa ma manca da `fine_grid_stats.csv`.

In [19]:
from pathlib import Path
import re
import pandas as pd
import numpy as np
from datetime import datetime

pd.set_option("display.max_columns", 120)
pd.set_option("display.max_colwidth", 240)
pd.set_option("display.width", 200)

ROOT = Path("/home/fbellisardi/code/topolity")
DATA_ROOT = ROOT / "data" / "data_processed"
SCRIPT = ROOT / "pipeline_production" / "dem_extractor_fine_grid.py"

# Same configuration as your bash defaults
STEP_METERS = 500
NUM_POINTS = 5
ROT_ANGLES = [-20, -15, -10, -5, 5, 10, 15, 20]
NS_SCALES = [1.02, 1.05, 1.08, 1.12]
EW_SCALES = [1.02, 1.05, 1.08, 1.12]

# Suggested rerun settings
TIME_LIMIT = "168:00"
MEM_GB = 128
CPUS = 4
WORKERS = 1
LAND_CHECK = "sample"
LOW_MEMORY = True
USE_FUA = True
DEM_MODE = "tree"

DATA_ROOT

PosixPath('/home/fbellisardi/code/topolity/data/data_processed')

In [20]:
def normalize_rotation_angles(angles_deg):
    normalized = []
    for angle in angles_deg or []:
        a = float(angle) % 360.0
        if a > 180.0:
            a -= 360.0
        normalized.append(a)
    return sorted(set(normalized))


def format_scale_token(scale_factor):
    return f"{float(scale_factor):.3f}".replace(".", "p")


def variant_sort_key(v):
    v = str(v)
    if v == "original":
        return (0, 0, 0, "")
    m = re.match(r"trans_(\d+)m_a([+-]\d+)", v)
    if m:
        return (1, int(m.group(1)), int(m.group(2)), v)
    m = re.match(r"rot_([+-]\d+p\d+)deg", v)
    if m:
        val = float(m.group(1).replace("p", "."))
        return (2, abs(val), val, v)
    m = re.match(r"scale_(ns|ew)_(\d+p\d+)", v)
    if m:
        axis = 0 if m.group(1) == "ns" else 1
        val = float(m.group(2).replace("p", "."))
        return (3, axis, val, v)
    return (9, 0, 0, v)


def expected_rotation_variants(rotation_angles):
    variants = []
    for angle in normalize_rotation_angles(rotation_angles):
        if np.isclose(angle, 0.0):
            continue
        variants.append(f"rot_{angle:+.2f}deg".replace(".", "p"))
    return variants


def expected_scale_variants(ns_scales, ew_scales):
    variants = []
    for scale in sorted(set(float(s) for s in ns_scales)):
        if not np.isclose(scale, 1.0):
            variants.append(f"scale_ns_{format_scale_token(scale)}")
    for scale in sorted(set(float(s) for s in ew_scales)):
        if not np.isclose(scale, 1.0):
            variants.append(f"scale_ew_{format_scale_token(scale)}")
    return variants


def expected_translation_variants_from_stats_or_default(stats_df=None, step_meters=500, num_points=5):
    # The code may produce names such as 1499m due to int rounding.
    # Therefore, include both the default expected names and any translation names already present in stats.
    default = ["original"]
    for i in range(1, num_points + 1):
        d = i * step_meters
        for a in [0, 90, 180, 270]:
            default.append(f"trans_{d}m_a{a:+04d}")

    if stats_df is None or stats_df.empty or "variant" not in stats_df.columns:
        return default

    stats_vars = stats_df["variant"].dropna().astype(str)
    trans_seen = [v for v in stats_vars if v == "original" or v.startswith("trans_")]
    return sorted(set(default) | set(trans_seen), key=variant_sort_key)


def expected_variants_for_city(stats_df=None):
    translations = expected_translation_variants_from_stats_or_default(stats_df, STEP_METERS, NUM_POINTS)
    rotations = expected_rotation_variants(ROT_ANGLES)
    scales = expected_scale_variants(NS_SCALES, EW_SCALES)
    return sorted(set(translations + rotations + scales), key=variant_sort_key)


def list_city_dirs(data_root=DATA_ROOT):
    return sorted([p for p in data_root.iterdir() if p.is_dir() and (p / "data_useful.csv").exists()])


def read_stats(city_dir):
    stats_path = city_dir / "graphs_fine_grid" / "fine_grid_stats.csv"
    if not stats_path.exists() or stats_path.stat().st_size == 0:
        return pd.DataFrame(), stats_path
    try:
        return pd.read_csv(stats_path), stats_path
    except Exception as e:
        print(f"[warning] could not read {stats_path}: {e}")
        return pd.DataFrame(), stats_path


def pkl_variants(city_dir):
    gdir = city_dir / "graphs_fine_grid"
    out = set()
    if not gdir.exists():
        return out
    for p in gdir.glob("graph_*.pkl"):
        out.add(p.name[len("graph_"):-len(".pkl")])
    return out


def latest_file_info(city_dir):
    gdir = city_dir / "graphs_fine_grid"
    if not gdir.exists():
        return None, None
    files = [p for p in gdir.iterdir() if p.is_file()]
    if not files:
        return None, None
    latest = max(files, key=lambda p: p.stat().st_mtime)
    return datetime.fromtimestamp(latest.stat().st_mtime), latest.name


def bool_series_on_land(s):
    return s.astype(str).str.lower().map({
        "true": True, "false": False,
        "1": True, "0": False,
        "yes": True, "no": False,
    })


def compact_join(values, max_chars=800):
    txt = ", ".join(list(values))
    if len(txt) <= max_chars:
        return txt
    return txt[:max_chars] + "..."

In [21]:
def audit_city(city_dir):
    city = city_dir.name
    stats_df, stats_path = read_stats(city_dir)
    pkl_vars = pkl_variants(city_dir)
    latest_mtime, latest_file = latest_file_info(city_dir)

    expected = set(expected_variants_for_city(stats_df))
    stats_vars = set(stats_df["variant"].dropna().astype(str)) if not stats_df.empty and "variant" in stats_df.columns else set()

    sea_rejected = set()
    valid_stats = set()
    unknown_land_stats = set()

    if not stats_df.empty and "variant" in stats_df.columns:
        tmp = stats_df.copy()
        if "on_land" in tmp.columns:
            tmp["_on_land_bool"] = bool_series_on_land(tmp["on_land"])
            sea_rejected = set(tmp.loc[tmp["_on_land_bool"] == False, "variant"].dropna().astype(str))
            valid_stats = set(tmp.loc[tmp["_on_land_bool"] == True, "variant"].dropna().astype(str))
            unknown_land_stats = set(tmp.loc[tmp["_on_land_bool"].isna(), "variant"].dropna().astype(str))
        else:
            valid_stats = stats_vars

    # Processed = present in stats, including on_land=False rejected variants
    processed = stats_vars
    missing_real = expected - processed

    valid_without_pkl = valid_stats - pkl_vars
    pkl_without_stats = pkl_vars - stats_vars

    extra_stats = stats_vars - expected
    extra_pkl = pkl_vars - expected

    if len(stats_vars) == 0 and len(pkl_vars) == 0:
        status = "not_started"
    elif len(missing_real) == 0 and len(valid_without_pkl) == 0:
        status = "done_or_rejected"
    elif len(missing_real) == 0 and len(valid_without_pkl) > 0:
        status = "stats_without_pkl_check"
    else:
        status = "partial_to_resume"

    return {
        "city": city,
        "status": status,
        "expected_total": len(expected),
        "expected_translations": len([v for v in expected if v == "original" or v.startswith("trans_")]),
        "expected_rotations": len([v for v in expected if v.startswith("rot_")]),
        "expected_scales": len([v for v in expected if v.startswith("scale_")]),
        "stats_rows": len(stats_df),
        "stats_variants": len(stats_vars),
        "pkl_count": len(pkl_vars),
        "valid_completed_count": len(valid_stats & pkl_vars),
        "sea_rejected_count": len(sea_rejected),
        "missing_real_count": len(missing_real),
        "valid_without_pkl_count": len(valid_without_pkl),
        "pkl_without_stats_count": len(pkl_without_stats),
        "extra_stats_count": len(extra_stats),
        "extra_pkl_count": len(extra_pkl),
        "latest_mtime": latest_mtime,
        "latest_file": latest_file,
        "missing_real_variants": compact_join(sorted(missing_real, key=variant_sort_key)),
        "valid_without_pkl_variants": compact_join(sorted(valid_without_pkl, key=variant_sort_key)),
        "sea_rejected_variants": compact_join(sorted(sea_rejected, key=variant_sort_key)),
        "extra_stats_variants": compact_join(sorted(extra_stats, key=variant_sort_key), max_chars=350),
        "extra_pkl_variants": compact_join(sorted(extra_pkl, key=variant_sort_key), max_chars=350),
    }


rows = [audit_city(city_dir) for city_dir in list_city_dirs(DATA_ROOT)]
audit = pd.DataFrame(rows).sort_values(
    ["status", "missing_real_count", "valid_without_pkl_count", "city"],
    ascending=[True, False, False, True],
).reset_index(drop=True)

audit

,city,status,expected_total,expected_translations,expected_rotations,expected_scales,stats_rows,stats_variants,pkl_count,valid_completed_count,sea_rejected_count,missing_real_count,valid_without_pkl_count,pkl_without_stats_count,extra_stats_count,extra_pkl_count,latest_mtime,latest_file,missing_real_variants,valid_without_pkl_variants,sea_rejected_variants,extra_stats_variants,extra_pkl_variants
0,amsterdam,done_or_rejected,37,21,8,8,37,37,37,37,0,0,0,0,0,0,2026-04-29 11:26:15.192732,fine_grid_gravitational_work.pdf,,,,,
1,bandung,done_or_rejected,37,21,8,8,37,37,37,37,0,0,0,0,0,0,2026-04-29 12:06:15.273475,fine_grid_gravitational_work.pdf,,,,,
2,bogota,done_or_rejected,37,21,8,8,37,37,37,37,0,0,0,0,0,0,2026-04-29 12:19:30.474786,fine_grid_gravitational_work.pdf,,,,,
3,caracas,done_or_rejected,37,21,8,8,37,37,36,36,1,0,0,0,0,0,2026-04-29 12:35:42.857298,fine_grid_gravitational_work.pdf,,,rot_-20p00deg,,
4,chicago,done_or_rejected,37,21,8,8,37,37,37,37,0,0,0,0,0,0,2026-05-03 09:42:27.658141,fine_grid_stats.csv,,,,,
5,moscou,done_or_rejected,37,21,8,8,49,49,49,49,0,0,0,0,12,12,2026-05-01 05:48:46.407484,fine_grid_stats.csv,,,,"rot_-0p50deg, rot_+0p50deg, rot_-1p00deg, rot_+1p00deg, rot_-2p00deg, rot_+2p00deg, rot_-25p00deg, rot_+25p00deg, rot_-30p00deg, rot_+30p00deg, rot_-45p00deg, rot_+45p00deg","rot_-0p50deg, rot_+0p50deg, rot_-1p00deg, rot_+1p00deg, rot_-2p00deg, rot_+2p00deg, rot_-25p00deg, rot_+25p00deg, rot_-30p00deg, rot_+30p00deg, rot_-45p00deg, rot_+45p00deg"
6,santiago,done_or_rejected,37,21,8,8,49,46,159,46,0,0,0,113,9,122,2026-04-30 13:08:52.055308,fine_grid_gravitational_work.pdf,,,,"rot_+0p50deg, rot_+1p00deg, rot_+2p00deg, rot_-25p00deg, rot_+25p00deg, rot_-30p00deg, rot_+30p00deg, rot_-45p00deg, rot_+45p00deg","trans_50m_a+000, trans_50m_a+090, trans_50m_a+180, trans_50m_a+270, trans_100m_a+000, trans_100m_a+090, trans_100m_a+180, trans_100m_a+270, trans_150m_a+000, trans_150m_a+090, trans_150m_a+180, trans_150m_a+270, trans_200m_a+000, trans_..."
7,hongkong,partial_to_resume,37,21,8,8,1,1,0,0,1,36,0,0,0,0,2026-04-18 22:15:49.567302,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_...",,original,,
8,vancouver,partial_to_resume,39,23,8,8,3,3,0,0,3,36,0,0,0,0,2026-04-20 23:34:00.510090,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_...",,"original, trans_499m_a+000, trans_999m_a+000",,
9,pekin,partial_to_resume,37,21,8,8,2,2,2,2,0,35,0,0,0,0,2026-04-30 05:43:18.941112,fine_grid_gravitational_work.pdf,"trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",,,,
10,riodejaneiro,partial_to_resume,37,21,8,8,2,2,0,0,2,35,0,0,0,0,2026-04-20 03:23:16.377474,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",,"original, trans_500m_a+180",,
11,sandiego,partial_to_resume,37,21,8,8,3,3,0,0,3,34,0,0,0,0,2026-04-20 15:51:53.013618,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000...",,"original, trans_500m_a+000, trans_500m_a+090",,
12,sanfrancisco,partial_to_resume,37,21,8,8,3,3,0,0,3,34,0,0,0,0,2026-04-20 14:14:03.660885,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000...",,"original, trans_500m_a+180, trans_500m_a+270",,
13,seoul,partial_to_resume,37,21,8,8,3,3,0,0,3,34,0,0,0,0,2026-04-20 16:15:35.519376,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",,"original, trans_500m_a+090, rot_+15p00deg",,
14,dublin,partial_to_resume,40,24,8,8,7,7,0,0,7,33,0,0,0,0,2026-04-19 00:15:56.029286,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m...",,"original, trans_499m_a+180, trans_500m_a+270, trans_999m_a+180, trans_1500m_a+180, trans_1999m_a+180, trans_2500m_a+180",,
15,istanbul,partial_to_resume,38,22,8,8,7,7,0,0,7,31,0,0,0,0,2026-04-19 02:49:24.606321,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m...",,"original, trans_499m_a+000, trans_500m_a+090, trans_1000m_a+090, trans_1500m_a+090, trans_2000m_a+090, trans_2500m_a+090",,
16,lisbon,partial_to_resume,37,21,8,8,6,6,0,0,6,31,0,0,0,0,2026-04-19 09:03:55.692942,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",,"original, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+180, rot_-5p00deg",,
17,newyork,partial_to_resume,37,21,8,8,6,6,0,0,6,31,0,0,0,0,2026-04-21 13:49:33.481356,fine_grid_stats.csv,"trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",,"original, trans_500m_a+000, trans_500m_a+270, trans_1000m_a+270, trans_1500m_a+000, scale_ew_1p020",,
18,shanghai,partial_to_resume,37,21,8,8,6,6,0,0,6,31,0,0,0,0,2026-04-20 23:36:15.785117,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m...",,"original, trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+180, trans_2000m_a+180, trans_2500m_a+180",,
19,taipei,partial_to_resume,37,21,8,8,6,6,0,0,6,31,0,0,0,0,2026-04-20 22:38:33.213222,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2500m...",,"original, trans_500m_a+270, trans_1000m_a+270, trans_1500m_a+270, trans_2000m_a+270, trans_2500m_a+270",,
20,barcelone,partial_to_resume,41,25,8,8,16,16,14,11,5,28,0,3,3,3,2026-04-29 11:33:23.995022,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m...",,"rot_-0p50deg, rot_+0p50deg, rot_+1p00deg, scale_ns_1p020, scale_ew_1p020","rot_-0p50deg, rot_+0p50deg, rot_+1p00deg","trans_50m_a+255, trans_100m_a+255, trans_150m_a+255"
21,sydney,partial_to_resume,37,21,8,8,9,9,0,0,9,28,0,0,0,0,2026-04-21 04:41:22.280238,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m...",,"original, trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+180, trans_2000m_a+180, trans_2500m_a+180, rot_+5p00deg, rot_+10p00deg, scale_ns_1p120",,
22,dallas,partial_to_resume,38,22,8,8,11,11,11,11,0,27,0,0,0,0,2026-05-05 11:55:29.056098,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg,...",,,,
23,houston,partial_to_resume,37,21,8,8,10,10,0,0,10,27,0,0,0,0,2026-04-19 10:22:44.350319,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",,"original, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+270, rot_+15p00deg, rot_+20p00deg, scale_ns_1p050, scale_ns_1p120, scale_ew_1p080",,
24,londres,partial_to_resume,37,21,8,8,13,13,3,3,10,24,0,0,0,0,2026-04-29 19:16:48.983718,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_+5p00d...",,"original, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2500m_a+180, rot_-5p00deg",,
25,lima,partial_to_resume,37,21,8,8,14,14,5,5,9,23,0,0,0,0,2026-04-29 18:25:04.458840,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p...",,"original, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+090, trans_1500m_a+090, trans_2000m_a+090, trans_2500m_a+090, scale_ns_1p020, scale_ns_1p050",,
26,losangeles,partial_to_resume,37,21,8,8,14,14,0,0,14,23,0,0,0,0,2026-04-21 01:29:25.642096,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500...",,"original, trans_500m_a+000, trans_500m_a+090, trans_1000m_a+090, trans_1500m_a+090, trans_2000m_a+090, trans_2500m_a+090, rot_-5p00deg, rot_-15p00deg, rot_-20p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120",,
27,rome,partial_to_resume,37,21,8,8,20,20,48,15,5,22,0,33,5,34,2026-04-30 08:33:28.831811,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_...",,"rot_-1p00deg, rot_-2p00deg, rot_-20p00deg, rot_-25p00deg, rot_-30p00deg","rot_-0p50deg, rot_-1p00deg, rot_-2p00deg, rot_-25p00deg, rot_-30p00deg","trans_100m_a+000, trans_100m_a+090, trans_200m_a+000, trans_200m_a+090, trans_300m_a+000, trans_300m_a+090, trans_400m_a+000, trans_400m_a+090, trans_500m_a+320, trans_600m_a+000, trans_600m_a+090, trans_700m_a+000, trans_700m_a+090, tr..."
28,boston,partial_to_resume,37,21,8,8,16,16,1,1,15,21,0,0,0,0,2026-04-19 00:02:29.243434,fine_grid_stats.csv,"trans_500m_a+000, trans_1000m_a+000, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_-5p00deg, rot_-15p00deg, rot_+15p00deg, rot...",,"trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, scale...",,
29,miami,partial_to_resume,37,21,8,8,17,17,0,0,17,20,0,0,0,0,2026-04-21 01:51:32.230996,fine_grid_stats.csv,"trans_1000m_a+000, trans_1500m_a+000, trans_2000m_a+000, trans_2500m_a+000, trans_2500m_a+090, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_n...",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+090, trans_2000m_a+180, tr...",,
30,montreal,partial_to_resume,37,21,8,8,17,17,0,0,17,20,0,0,0,0,2026-04-19 19:05:23.318788,fine_grid_stats.csv,"trans_500m_a+180, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+090, trans_2500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot...",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2500m_a+000, trans_2500m_a+270, rot_+5p00deg, rot_+15p00deg, scale_ns_1...",,
31,osaka,partial_to_resume,38,22,8,8,18,18,0,0,18,20,0,0,0,0,2026-04-24 10:43:15.494764,fine_grid_stats.csv,"trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+270, trans_2000m_a+090, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_+20...",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+270, trans_2499m_a+000, r...",,
32,phoenix,partial_to_resume,45,29,8,8,29,29,29,29,0,20,0,0,4,4,2026-05-06 11:06:33.995796,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p...",,,"rot_-2p00deg, rot_-25p00deg, rot_-30p00deg, rot_-45p00deg","rot_-2p00deg, rot_-25p00deg, rot_-30p00deg, rot_-45p00deg"
33,santodomingo,partial_to_resume,37,21,8,8,17,17,5,5,12,20,0,0,0,0,2026-04-30 13:11:14.954752,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, ...",,"original, trans_500m_a+000, trans_1000m_a+180, trans_1500m_a+180, trans_2000m_a+180, rot_+5p00deg, scale_ns_1p020, scale_ns_1p050, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120",,
34,saintpetersbourg,partial_to_resume,37,21,8,8,18,18,0,0,18,19,0,0,0,0,2026-04-20 13:15:36.014170,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_+10p00deg, rot_+...",,"original, trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, rot_-10p00deg, rot_-15p00deg, rot_-20p...",,
35,buenosaires,partial_to_resume,37,21,8,8,19,19,10,10,9,18,0,0,0,0,2026-04-29 13:06:18.584738,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_...",,"original, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120, scale_ew_1p020",,
36,nagoya,partial_to_resume,37,21,8,8,19,19,0,0,19,18,0,0,0,0,2026-04-21 10:16:26.668633,fine_grid_stats.csv,"trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20...",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2500m_a+090, rot_+5p00deg, rot_+1...",,
37,paris,partial_to_resume,37,21,8,8,23,23,88,22,1,16,0,66,2,63,2026-05-06 15:03:23.861425,fine_grid_stats.csv,"rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_...",,rot_-45p00deg,"rot_-2p00deg, rot_-45p00deg","trans_100m_a+000, trans_100m_a+090, trans_100m_a+180, trans_100m_a+270, trans_200m_a+000, trans_200m_a+090, trans_200m_a+180, trans_200m_a+270, trans_300m_a+000, trans_300m_a+090, trans_300m_a+180, trans_300m_a+270, trans_400m_a+000, tr..."
38,singapour,partial_to_resume,37,21,8,8,21,21,4,4,17,16,0,0,0,0,2026-04-30 14:47:33.108387,fine_grid_gravitational_work.pdf,"trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120, scale_ew_1p0...",,"original, trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1500m_a+180, trans_2000m_a+180, trans_2500m_a+090, trans_2500m_a+180, rot_+5p00deg, rot_+10p00deg, rot_-15p00deg, rot_-20p00deg,...",,
39,bangkok,partial_to_resume,39,23,8,8,26,26,0,0,26,13,0,0,0,0,2026-04-19 16:12:59.646235,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+180, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1499m_a+000, trans_1499m_a+180, trans_1500m_a+090, trans_1500m_a+270, tr...",,
40,manille,partial_to_resume,44,28,8,8,31,31,5,5,26,13,0,0,0,0,2026-04-29 20:14:52.508848,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_-15p00deg, rot_+20p00deg, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120",,"original, trans_499m_a+180, trans_500m_a+090, trans_500m_a+270, trans_999m_a+180, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+090, trans_2000m_a+270, trans_2499m_a+180, tr...",,
41,stockholm,partial_to_resume,37,21,8,8,25,25,0,0,25,12,0,0,0,0,2026-04-20 19:37:03.722972,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120",,"original, trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+180, trans_2000m_a+270, tr...",,

## Città da rilanciare

Queste sono le città con varianti attese ma non presenti in `fine_grid_stats.csv`.
Il conteggio include anche rotazioni e scale transformations.

In [22]:
to_rerun = audit[audit["missing_real_count"] > 0].copy()
to_rerun = to_rerun.sort_values(["missing_real_count", "city"], ascending=[False, True]).reset_index(drop=True)

cols = [
    "city", "status",
    "expected_total", "expected_translations", "expected_rotations", "expected_scales",
    "missing_real_count", "valid_completed_count", "sea_rejected_count",
    "stats_rows", "pkl_count", "latest_mtime", "latest_file",
    "missing_real_variants",
]
to_rerun[cols]

,city,status,expected_total,expected_translations,expected_rotations,expected_scales,missing_real_count,valid_completed_count,sea_rejected_count,stats_rows,pkl_count,latest_mtime,latest_file,missing_real_variants
0,hongkong,partial_to_resume,37,21,8,8,36,0,1,1,0,2026-04-18 22:15:49.567302,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_..."
1,vancouver,partial_to_resume,39,23,8,8,36,0,3,3,0,2026-04-20 23:34:00.510090,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_..."
2,pekin,partial_to_resume,37,21,8,8,35,2,0,2,2,2026-04-30 05:43:18.941112,fine_grid_gravitational_work.pdf,"trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m..."
3,riodejaneiro,partial_to_resume,37,21,8,8,35,0,2,2,0,2026-04-20 03:23:16.377474,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m..."
4,sandiego,partial_to_resume,37,21,8,8,34,0,3,3,0,2026-04-20 15:51:53.013618,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000..."
5,sanfrancisco,partial_to_resume,37,21,8,8,34,0,3,3,0,2026-04-20 14:14:03.660885,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000..."
6,seoul,partial_to_resume,37,21,8,8,34,0,3,3,0,2026-04-20 16:15:35.519376,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m..."
7,dublin,partial_to_resume,40,24,8,8,33,0,7,7,0,2026-04-19 00:15:56.029286,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m..."
8,istanbul,partial_to_resume,38,22,8,8,31,0,7,7,0,2026-04-19 02:49:24.606321,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m..."
9,lisbon,partial_to_resume,37,21,8,8,31,0,6,6,0,2026-04-19 09:03:55.692942,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500..."
10,newyork,partial_to_resume,37,21,8,8,31,0,6,6,0,2026-04-21 13:49:33.481356,fine_grid_stats.csv,"trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500..."
11,shanghai,partial_to_resume,37,21,8,8,31,0,6,6,0,2026-04-20 23:36:15.785117,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m..."
12,taipei,partial_to_resume,37,21,8,8,31,0,6,6,0,2026-04-20 22:38:33.213222,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2500m..."
13,barcelone,partial_to_resume,41,25,8,8,28,11,5,16,14,2026-04-29 11:33:23.995022,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m..."
14,sydney,partial_to_resume,37,21,8,8,28,0,9,9,0,2026-04-21 04:41:22.280238,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m..."
15,dallas,partial_to_resume,38,22,8,8,27,11,0,11,11,2026-05-05 11:55:29.056098,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg,..."
16,houston,partial_to_resume,37,21,8,8,27,0,10,10,0,2026-04-19 10:22:44.350319,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500..."
17,londres,partial_to_resume,37,21,8,8,24,3,10,13,3,2026-04-29 19:16:48.983718,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_+5p00d..."
18,lima,partial_to_resume,37,21,8,8,23,5,9,14,5,2026-04-29 18:25:04.458840,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p..."
19,losangeles,partial_to_resume,37,21,8,8,23,0,14,14,0,2026-04-21 01:29:25.642096,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500..."
20,rome,partial_to_resume,37,21,8,8,22,15,5,20,48,2026-04-30 08:33:28.831811,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_..."
21,boston,partial_to_resume,37,21,8,8,21,1,15,16,1,2026-04-19 00:02:29.243434,fine_grid_stats.csv,"trans_500m_a+000, trans_1000m_a+000, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_-5p00deg, rot_-15p00deg, rot_+15p00deg, rot..."
22,miami,partial_to_resume,37,21,8,8,20,0,17,17,0,2026-04-21 01:51:32.230996,fine_grid_stats.csv,"trans_1000m_a+000, trans_1500m_a+000, trans_2000m_a+000, trans_2500m_a+000, trans_2500m_a+090, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_n..."
23,montreal,partial_to_resume,37,21,8,8,20,0,17,17,0,2026-04-19 19:05:23.318788,fine_grid_stats.csv,"trans_500m_a+180, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+090, trans_2500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot..."
24,osaka,partial_to_resume,38,22,8,8,20,0,18,18,0,2026-04-24 10:43:15.494764,fine_grid_stats.csv,"trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+270, trans_2000m_a+090, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_+20..."
25,phoenix,partial_to_resume,45,29,8,8,20,29,0,29,29,2026-05-06 11:06:33.995796,fine_grid_stats.csv,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p..."
26,santodomingo,partial_to_resume,37,21,8,8,20,5,12,17,5,2026-04-30 13:11:14.954752,fine_grid_gravitational_work.pdf,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, ..."
27,saintpetersbourg,partial_to_resume,37,21,8,8,19,0,18,18,0,2026-04-20 13:15:36.014170,fine_grid_stats.csv,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_+10p00deg, rot_+..."
28,buenosaires,partial_to_resume,37,21,8,8,18,10,9,19,10,2026-04-29 13:06:18.584738,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_..."
29,nagoya,partial_to_resume,37,21,8,8,18,0,19,19,0,2026-04-21 10:16:26.668633,fine_grid_stats.csv,"trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20..."
30,paris,partial_to_resume,37,21,8,8,16,22,1,23,88,2026-05-06 15:03:23.861425,fine_grid_stats.csv,"rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_..."
31,singapour,partial_to_resume,37,21,8,8,16,4,17,21,4,2026-04-30 14:47:33.108387,fine_grid_gravitational_work.pdf,"trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120, scale_ew_1p0..."
32,bangkok,partial_to_resume,39,23,8,8,13,0,26,26,0,2026-04-19 16:12:59.646235,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+180, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120"
33,manille,partial_to_resume,44,28,8,8,13,5,26,31,5,2026-04-29 20:14:52.508848,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_-15p00deg, rot_+20p00deg, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120"
34,stockholm,partial_to_resume,37,21,8,8,12,0,25,25,0,2026-04-20 19:37:03.722972,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120"
35,tokyo,partial_to_resume,37,21,8,8,12,0,25,25,0,2026-04-27 13:50:41.159472,fine_grid_stats.csv,"trans_1000m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120"
36,djakarta,partial_to_resume,39,23,8,8,11,5,23,28,5,2026-04-29 17:08:19.927794,fine_grid_gravitational_work.pdf,"trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p120"
37,bruxelles,partial_to_resume,47,31,8,8,10,37,0,37,37,2026-04-29 12:20:31.905977,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_1500m_a+000, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180"
38,kualalumpur,partial_to_resume,39,23,8,8,10,5,24,29,5,2026-04-29 17:30:23.596583,fine_grid_gravitational_work.pdf,"trans_1500m_a+000, trans_1500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ew_1p120"
39,philadelphie,partial_to_resume,37,21,8,8,10,0,27,27,0,2026-04-20 02:28:51.367778,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg"
40,washington,partial_to_resume,37,21,8,8,10,0,27,27,0,2026-04-22 15:03:25.496701,fine_grid_stats.csv,"trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+090, trans_2500m_a+000, rot_-5p00deg, rot_-10p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p120"
41,saopaulo,partial_to_resume,37,21,8,8,9,34,2,36,34,2026-05-06 07:50:35.226900,fine_grid_stats.csv,"rot_+20p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120"
42,berlin,partial_to_resume,45,29,8,8,8,37,0,37,37,2026-04-29 12:28:16.454110,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180"
43,manchester,partial_to_resume,43,27,8,8,8,9,26,35,9,2026-04-29 20:14:19.167110,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+090, trans_2500m_a+180"
44,guadalajara,partial_to_resume,43,27,8,8,6,37,0,37,37,2026-04-29 18:10:34.369712,fine_grid_gravitational_work.pdf,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180"
45,mexico,partial_to_resume,37,21,8,8,5,44,0,44,44,2026-05-06 10:26:37.806668,fine_grid_stats.csv,"scale_ns_1p120, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120"
46,madrid,partial_to_resume,37,21,8,8,3,34,0,34,106,2026-05-06 05:19:48.600191,fine_grid_stats.csv,"scale_ew_1p050, scale_ew_1p080, scale_ew_1p120"
47,atlanta,partial_to_resume,39,23,8,8,2,37,0,37,173,2026-05-03 04:24:57.963103,fine_grid_gravitational_work.pdf,"trans_2500m_a+000, trans_2500m_a+180"
48,detroitwindsor,partial_to_resume,39,23,8,8,2,37,0,37,37,2026-04-29 23:59:54.122949,fine_grid_gravitational_work.pdf,"trans_1500m_a+000, trans_1500m_a+180"
49,milan,partial_to_resume,39,23,8,8,2,49,0,49,59,2026-04-29 20:41:51.245169,fine_grid_gravitational_work.pdf,"trans_1500m_a+000, trans_1500m_a+180"
50,toronto,partial_to_resume,39,23,8,8,2,49,0,49,49,2026-05-05 07:44:54.755681,fine_grid_stats.csv,"trans_1500m_a+000, trans_1500m_a+180"

## Città complete o rigettate correttamente

Qui `missing_real_count = 0`. Se `sea_rejected_count` è alto è normale per città costiere/isole.

In [23]:
done = audit[audit["missing_real_count"] == 0].copy()
done = done.sort_values(["status", "sea_rejected_count", "city"], ascending=[True, False, True]).reset_index(drop=True)

done[[
    "city", "status", "expected_total", "valid_completed_count",
    "sea_rejected_count", "valid_without_pkl_count",
    "stats_rows", "pkl_count", "latest_mtime", "latest_file"
]]

        city            status  expected_total  valid_completed_count  sea_rejected_count  valid_without_pkl_count  stats_rows  pkl_count               latest_mtime                       latest_file
0    caracas  done_or_rejected              37                     36                   1                        0          37         36 2026-04-29 12:35:42.857298  fine_grid_gravitational_work.pdf
1  amsterdam  done_or_rejected              37                     37                   0                        0          37         37 2026-04-29 11:26:15.192732  fine_grid_gravitational_work.pdf
2    bandung  done_or_rejected              37                     37                   0                        0          37         37 2026-04-29 12:06:15.273475  fine_grid_gravitational_work.pdf
3     bogota  done_or_rejected              37                     37                   0                        0          37         37 2026-04-29 12:19:30.474786  fine_grid_gravitational_work.pdf
4    chicago  done_or_rejected              37                     37                   0                        0          37         37 2026-05-03 09:42:27.658141               fine_grid_stats.csv
5     moscou  done_or_rejected              37                     49                   0                        0          49         49 2026-05-01 05:48:46.407484               fine_grid_stats.csv
6   santiago  done_or_rejected              37                     46                   0                        0          49        159 2026-04-30 13:08:52.055308  fine_grid_gravitational_work.pdf

## Casi sospetti

`valid_without_pkl_count > 0` significa: nel CSV la variante è `on_land=True`, ma manca il pickle. Queste vanno controllate o rilanciate.

In [24]:
suspicious = audit[
    (audit["valid_without_pkl_count"] > 0) |
    (audit["pkl_without_stats_count"] > 0)
].copy()

suspicious[[
    "city", "status", "valid_without_pkl_count", "pkl_without_stats_count",
    "valid_without_pkl_variants", "latest_mtime", "latest_file"
]]

         city             status  valid_without_pkl_count  pkl_without_stats_count valid_without_pkl_variants               latest_mtime                       latest_file
6    santiago   done_or_rejected                        0                      113                            2026-04-30 13:08:52.055308  fine_grid_gravitational_work.pdf
20  barcelone  partial_to_resume                        0                        3                            2026-04-29 11:33:23.995022  fine_grid_gravitational_work.pdf
27       rome  partial_to_resume                        0                       33                            2026-04-30 08:33:28.831811  fine_grid_gravitational_work.pdf
37      paris  partial_to_resume                        0                       66                            2026-05-06 15:03:23.861425               fine_grid_stats.csv
53     madrid  partial_to_resume                        0                       72                            2026-05-06 05:19:48.600191               fine_grid_stats.csv
54    atlanta  partial_to_resume                        0                      136                            2026-05-03 04:24:57.963103  fine_grid_gravitational_work.pdf
56      milan  partial_to_resume                        0                       10                            2026-04-29 20:41:51.245169  fine_grid_gravitational_work.pdf

## Comandi di rilancio

I comandi usano `--resume`, quindi saltano ciò che è già presente nel CSV.

In [26]:
def build_rerun_command(city):
    low_memory_flag = " --low-memory" if LOW_MEMORY else ""
    fua_flag = " --use-fua" if USE_FUA else ""
    rot = " ".join(str(x) for x in ROT_ANGLES)
    ns = " ".join(str(x) for x in NS_SCALES)
    ew = " ".join(str(x) for x in EW_SCALES)

    return (
        f"runlog -t {TIME_LIMIT} -m {MEM_GB} -c {CPUS} -j fg_{city}_resume "
        f"conda run --no-capture-output -n geo_flow "
        f"python -u {SCRIPT} "
        f"--city {city} "
        f"--step-meters {STEP_METERS} "
        f"--num-points {NUM_POINTS} "
        f"--rotation-angles {rot} "
        f"--ns-scale-factors {ns} "
        f"--ew-scale-factors {ew} "
        f"--workers {WORKERS} "
        f"--seed 42 "
        f"--resume "
        f"--dem-mode {DEM_MODE}"
        f"{low_memory_flag}"
        f"{fua_flag} "
        f"--land-check {LAND_CHECK}"
    )


rerun_commands = to_rerun[["city", "missing_real_count", "missing_real_variants"]].copy()
rerun_commands["command"] = rerun_commands["city"].apply(build_rerun_command)
rerun_commands

,city,missing_real_count,missing_real_variants,command
0,hongkong,36,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_...",runlog -t 168:00 -m 128 -c 4 -j fg_hongkong_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city hongkong --step-meters 500 --num-points 5 --rot...
1,vancouver,36,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_...",runlog -t 168:00 -m 128 -c 4 -j fg_vancouver_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city vancouver --step-meters 500 --num-points 5 --r...
2,pekin,35,"trans_500m_a+090, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",runlog -t 168:00 -m 128 -c 4 -j fg_pekin_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city pekin --step-meters 500 --num-points 5 --rotation-...
3,riodejaneiro,35,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",runlog -t 168:00 -m 128 -c 4 -j fg_riodejaneiro_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city riodejaneiro --step-meters 500 --num-points...
4,sandiego,34,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000...",runlog -t 168:00 -m 128 -c 4 -j fg_sandiego_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city sandiego --step-meters 500 --num-points 5 --rot...
5,sanfrancisco,34,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000...",runlog -t 168:00 -m 128 -c 4 -j fg_sanfrancisco_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city sanfrancisco --step-meters 500 --num-points...
6,seoul,34,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m...",runlog -t 168:00 -m 128 -c 4 -j fg_seoul_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city seoul --step-meters 500 --num-points 5 --rotation-...
7,dublin,33,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m...",runlog -t 168:00 -m 128 -c 4 -j fg_dublin_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city dublin --step-meters 500 --num-points 5 --rotatio...
8,istanbul,31,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m...",runlog -t 168:00 -m 128 -c 4 -j fg_istanbul_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city istanbul --step-meters 500 --num-points 5 --rot...
9,lisbon,31,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",runlog -t 168:00 -m 128 -c 4 -j fg_lisbon_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city lisbon --step-meters 500 --num-points 5 --rotatio...
10,newyork,31,"trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",runlog -t 168:00 -m 128 -c 4 -j fg_newyork_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city newyork --step-meters 500 --num-points 5 --rotat...
11,shanghai,31,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m...",runlog -t 168:00 -m 128 -c 4 -j fg_shanghai_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city shanghai --step-meters 500 --num-points 5 --rot...
12,taipei,31,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2500m...",runlog -t 168:00 -m 128 -c 4 -j fg_taipei_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city taipei --step-meters 500 --num-points 5 --rotatio...
13,barcelone,28,"trans_500m_a+000, trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m...",runlog -t 168:00 -m 128 -c 4 -j fg_barcelone_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city barcelone --step-meters 500 --num-points 5 --r...
14,sydney,28,"trans_500m_a+000, trans_500m_a+090, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m...",runlog -t 168:00 -m 128 -c 4 -j fg_sydney_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city sydney --step-meters 500 --num-points 5 --rotatio...
15,dallas,27,"trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg,...",runlog -t 168:00 -m 128 -c 4 -j fg_dallas_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city dallas --step-meters 500 --num-points 5 --rotatio...
16,houston,27,"trans_500m_a+000, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+090, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500...",runlog -t 168:00 -m 128 -c 4 -j fg_houston_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city houston --step-meters 500 --num-points 5 --rotat...
17,londres,24,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_+5p00d...",runlog -t 168:00 -m 128 -c 4 -j fg_londres_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city londres --step-meters 500 --num-points 5 --rotat...
18,lima,23,"trans_500m_a+180, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p...",runlog -t 168:00 -m 128 -c 4 -j fg_lima_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city lima --step-meters 500 --num-points 5 --rotation-an...
19,losangeles,23,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+000, trans_2500...",runlog -t 168:00 -m 128 -c 4 -j fg_losangeles_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city losangeles --step-meters 500 --num-points 5 -...
20,rome,22,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_...",runlog -t 168:00 -m 128 -c 4 -j fg_rome_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city rome --step-meters 500 --num-points 5 --rotation-an...
21,boston,21,"trans_500m_a+000, trans_1000m_a+000, trans_1500m_a+000, trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+270, rot_-5p00deg, rot_-15p00deg, rot_+15p00deg, rot...",runlog -t 168:00 -m 128 -c 4 -j fg_boston_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city boston --step-meters 500 --num-points 5 --rotatio...
22,miami,20,"trans_1000m_a+000, trans_1500m_a+000, trans_2000m_a+000, trans_2500m_a+000, trans_2500m_a+090, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_n...",runlog -t 168:00 -m 128 -c 4 -j fg_miami_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city miami --step-meters 500 --num-points 5 --rotation-...
23,montreal,20,"trans_500m_a+180, trans_1000m_a+090, trans_1000m_a+180, trans_1500m_a+090, trans_1500m_a+180, trans_2000m_a+090, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+090, trans_2500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot...",runlog -t 168:00 -m 128 -c 4 -j fg_montreal_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city montreal --step-meters 500 --num-points 5 --rot...
24,osaka,20,"trans_500m_a+180, trans_1000m_a+180, trans_1500m_a+270, trans_2000m_a+090, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_+20...",runlog -t 168:00 -m 128 -c 4 -j fg_osaka_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city osaka --step-meters 500 --num-points 5 --rotation-...
25,phoenix,20,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p...",runlog -t 168:00 -m 128 -c 4 -j fg_phoenix_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city phoenix --step-meters 500 --num-points 5 --rotat...
26,santodomingo,20,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+000, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, ...",runlog -t 168:00 -m 128 -c 4 -j fg_santodomingo_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city santodomingo --step-meters 500 --num-points...
27,saintpetersbourg,19,"trans_500m_a+180, trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+180, trans_2000m_a+270, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_+5p00deg, rot_+10p00deg, rot_+...",runlog -t 168:00 -m 128 -c 4 -j fg_saintpetersbourg_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city saintpetersbourg --step-meters 500 --nu...
28,buenosaires,18,"trans_500m_a+000, trans_500m_a+090, trans_1000m_a+000, trans_1000m_a+090, trans_1500m_a+000, trans_1500m_a+090, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, trans_2500m_a+090, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_...",runlog -t 168:00 -m 128 -c 4 -j fg_buenosaires_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city buenosaires --step-meters 500 --num-points 5...
29,nagoya,18,"trans_500m_a+270, trans_1000m_a+180, trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+180, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20...",runlog -t 168:00 -m 128 -c 4 -j fg_nagoya_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city nagoya --step-meters 500 --num-points 5 --rotatio...
30,paris,16,"rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p020, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120, scale_ew_1p020, scale_ew_1p050, scale_ew_1p080, scale_...",runlog -t 168:00 -m 128 -c 4 -j fg_paris_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city paris --step-meters 500 --num-points 5 --rotation-...
31,singapour,16,"trans_1000m_a+270, trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+000, trans_2500m_a+270, rot_-5p00deg, rot_-10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120, scale_ew_1p0...",runlog -t 168:00 -m 128 -c 4 -j fg_singapour_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city singapour --step-meters 500 --num-points 5 --r...
32,bangkok,13,"trans_1500m_a+000, trans_1500m_a+180, rot_-5p00deg, rot_+5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p050, scale_ns_1p080, scale_ns_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_bangkok_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city bangkok --step-meters 500 --num-points 5 --rotat...
33,manille,13,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180, rot_-15p00deg, rot_+20p00deg, scale_ew_1p050, scale_ew_1p080, scale_ew_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_manille_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city manille --step-meters 500 --num-points 5 --rotat...
34,stockholm,12,"trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2500m_a+000, rot_-5p00deg, rot_-10p00deg, rot_-15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_stockholm_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city stockholm --step-meters 500 --num-points 5 --r...
35,tokyo,12,"trans_1000m_a+000, trans_1500m_a+180, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+270, trans_2500m_a+270, rot_+5p00deg, rot_+10p00deg, rot_+15p00deg, rot_+20p00deg, scale_ns_1p080, scale_ns_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_tokyo_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city tokyo --step-meters 500 --num-points 5 --rotation-...
36,djakarta,11,"trans_2500m_a+000, trans_2500m_a+090, trans_2500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_djakarta_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city djakarta --step-meters 500 --num-points 5 --rot...
37,bruxelles,10,"trans_500m_a+000, trans_500m_a+180, trans_1000m_a+000, trans_1000m_a+180, trans_1500m_a+000, trans_1500m_a+180, trans_2000m_a+000, trans_2000m_a+180, trans_2500m_a+000, trans_2500m_a+180",runlog -t 168:00 -m 128 -c 4 -j fg_bruxelles_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city bruxelles --step-meters 500 --num-points 5 --r...
38,kualalumpur,10,"trans_1500m_a+000, trans_1500m_a+180, rot_-5p00deg, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ew_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_kualalumpur_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city kualalumpur --step-meters 500 --num-points 5...
39,philadelphie,10,"trans_1500m_a+000, trans_1500m_a+270, trans_2000m_a+000, trans_2000m_a+090, trans_2000m_a+180, rot_-10p00deg, rot_+10p00deg, rot_-15p00deg, rot_+15p00deg, rot_-20p00deg",runlog -t 168:00 -m 128 -c 4 -j fg_philadelphie_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city philadelphie --step-meters 500 --num-points...
40,washington,10,"trans_1500m_a+090, trans_1500m_a+270, trans_2000m_a+090, trans_2500m_a+000, rot_-5p00deg, rot_-10p00deg, rot_+15p00deg, rot_-20p00deg, rot_+20p00deg, scale_ns_1p120",runlog -t 168:00 -m 128 -c 4 -j fg_washington_resume conda run --no-capture-output -n geo_flow python -u /home/fbellisardi/code/topolity/pipeline_production/dem_extractor_fine_grid.py --city washington --step-meters 500 --num-points 5 -...

In [27]:
OUT_DIR = ROOT / "reports" / "fine_grid_audit"
OUT_DIR.mkdir(parents=True, exist_ok=True)

audit_path = OUT_DIR / "fine_grid_audit_v3_all_cities.csv"
rerun_path = OUT_DIR / "fine_grid_audit_v3_to_rerun.csv"
commands_path = OUT_DIR / "fine_grid_audit_v3_rerun_commands.sh"

audit.to_csv(audit_path, index=False)
to_rerun.to_csv(rerun_path, index=False)

with open(commands_path, "w") as f:
    f.write("#!/usr/bin/env bash\n")
    f.write("set -euo pipefail\n\n")
    for cmd in rerun_commands["command"]:
        f.write(cmd + "\n")

print("Saved:")
print(audit_path)
print(rerun_path)
print(commands_path)

Saved:
/home/fbellisardi/code/topolity/reports/fine_grid_audit/fine_grid_audit_v3_all_cities.csv
/home/fbellisardi/code/topolity/reports/fine_grid_audit/fine_grid_audit_v3_to_rerun.csv
/home/fbellisardi/code/topolity/reports/fine_grid_audit/fine_grid_audit_v3_rerun_commands.sh

## Ispezione dettagliata di una città

In [25]:
CITY = "dallas"

city_dir = DATA_ROOT / CITY
stats_df, _ = read_stats(city_dir)
expected = set(expected_variants_for_city(stats_df))
stats_vars = set(stats_df["variant"].dropna().astype(str)) if not stats_df.empty and "variant" in stats_df.columns else set()
pkl_vars = pkl_variants(city_dir)

detail = pd.DataFrame({"variant": sorted(expected | stats_vars | pkl_vars, key=variant_sort_key)})
detail["expected"] = detail["variant"].isin(expected)
detail["in_stats"] = detail["variant"].isin(stats_vars)
detail["has_pkl"] = detail["variant"].isin(pkl_vars)

if not stats_df.empty and "variant" in stats_df.columns:
    tmp = stats_df.copy()
    if "on_land" in tmp.columns:
        tmp["_on_land_bool"] = bool_series_on_land(tmp["on_land"])
        land_map = dict(zip(tmp["variant"].astype(str), tmp["_on_land_bool"]))
        detail["on_land"] = detail["variant"].map(land_map)
    else:
        detail["on_land"] = np.nan

detail["needs_rerun"] = detail["expected"] & (~detail["in_stats"])
detail.sort_values(["needs_rerun", "variant"], ascending=[False, True])

              variant  expected  in_stats  has_pkl on_land  needs_rerun
25      rot_+10p00deg      True     False    False     NaN         True
27      rot_+15p00deg      True     False    False     NaN         True
29      rot_+20p00deg      True     False    False     NaN         True
23       rot_+5p00deg      True     False    False     NaN         True
24      rot_-10p00deg      True     False    False     NaN         True
26      rot_-15p00deg      True     False    False     NaN         True
28      rot_-20p00deg      True     False    False     NaN         True
22       rot_-5p00deg      True     False    False     NaN         True
34     scale_ew_1p020      True     False    False     NaN         True
35     scale_ew_1p050      True     False    False     NaN         True
36     scale_ew_1p080      True     False    False     NaN         True
37     scale_ew_1p120      True     False    False     NaN         True
30     scale_ns_1p020      True     False    False     NaN         True
31     scale_ns_1p050      True     False    False     NaN         True
32     scale_ns_1p080      True     False    False     NaN         True
33     scale_ns_1p120      True     False    False     NaN         True
10  trans_1500m_a+000      True     False    False     NaN         True
12  trans_1500m_a+180      True     False    False     NaN         True
13  trans_1500m_a+270      True     False    False     NaN         True
14  trans_2000m_a+000      True     False    False     NaN         True
15  trans_2000m_a+090      True     False    False     NaN         True
16  trans_2000m_a+180      True     False    False     NaN         True
17  trans_2000m_a+270      True     False    False     NaN         True
18  trans_2500m_a+000      True     False    False     NaN         True
19  trans_2500m_a+090      True     False    False     NaN         True
20  trans_2500m_a+180      True     False    False     NaN         True
21  trans_2500m_a+270      True     False    False     NaN         True
0            original      True      True     True    True        False
5   trans_1000m_a+000      True      True     True    True        False
6   trans_1000m_a+090      True      True     True    True        False
7   trans_1000m_a+180      True      True     True    True        False
8   trans_1000m_a+270      True      True     True    True        False
9   trans_1499m_a+000      True      True     True    True        False
11  trans_1500m_a+090      True      True     True    True        False
1    trans_500m_a+000      True      True     True    True        False
2    trans_500m_a+090      True      True     True    True        False
3    trans_500m_a+180      True      True     True    True        False
4    trans_500m_a+270      True      True     True    True        False